Repository ral-facilities/datagateway, pull requests merged in 2021-11, with the labels that each got.

#884 Modified the query parameters of dataview and search plugins to refetch selection #864
  packages/datagateway-dataview/src/App.tsx
  packages/datagateway-search/src/App.tsx
Labels: bug, datagateway-search, datagateway-dataview

#906 Some contrast fixes #905
  packages/datagateway-common/src/homePage/homePage.component.tsx
  packages/datagateway-dataview/src/views/card/isis/isisDatasetsCardView.component.tsx
  packages/datagateway-dataview/src/views/card/isis/isisInvestigationsCardView.component.tsx
  packages/datagateway-dataview/src/views/detailsPanels/isis/investigationDetailsPanel.component.tsx
  packages/datagateway-dataview/src/views/landing/isis/isisBranding.component.tsx
  packages/datagateway-dataview/src/views/landing/isis/isisInvestigationLanding.component.tsx
  packages/datagateway-dataview/src/views/landing/isis/isisStudyLanding.component.tsx
  packages/datagateway-dataview/src/views/table/isis/__snapshots__/isisInvestigationsTable.component.test.tsx.snap
  packages/datagateway-dataview/src/views/table/isis/__snapshots__/isisMyDataTable.component.test.tsx.snap
  packages/datagateway-search/src/card/datasetSearchCardView.component.tsx
  packages/datagateway-search/src/card/investigationSearchCardView.component.tsx
Labels: accessibility

#910 Fix invalid date message and contrast #907
  packages/datagateway-common/src/api/index.test.tsx
  packages/datagateway-common/src/api/index.tsx
  packages/datagateway-common/src/table/columnFilters/__snapshots__/dateColumnFilter.component.test.tsx.snap
  packages/datagateway-common/src/table/columnFilters/dateColumnFilter.component.test.tsx
  packages/datagateway-common/src/table/columnFilters/dateColumnFilter.component.tsx
  packages/datagateway-common/src/table/table.component.tsx
  packages/datagateway-search/cypress/integration/searchBoxContainer.spec.ts
  packages/datagateway-search/public/res/default.json
  packages/datagateway-search/src/search/datePicker.component.test.tsx
  packages/datagateway-search/src/search/datePicker.component.tsx
Labels: bug, accessibility

#915 fix search tick focusing problem #911
  packages/datagateway-search/src/search/checkBoxes.component.tsx
Labels: bug, datagateway-search, accessibility

#917 #913 - Remove uneccessary includes and type filters
  packages/datagateway-dataview/cypress/integration/card/dls/visits.spec.ts
  packages/datagateway-dataview/src/views/card/datasetCardView.component.test.tsx
  packages/datagateway-dataview/src/views/card/datasetCardView.component.tsx
  packages/datagateway-dataview/src/views/card/dls/__snapshots__/dlsDatasetsCardView.component.test.tsx.snap
  packages/datagateway-dataview/src/views/card/dls/__snapshots__/dlsVisitsCardView.component.test.tsx.snap
  packages/datagateway-dataview/src/views/card/dls/dlsDatasetsCardView.component.test.tsx
  packages/datagateway-dataview/src/views/card/dls/dlsDatasetsCardView.component.tsx
  packages/datagateway-dataview/src/views/card/dls/dlsVisitsCardView.component.test.tsx
  packages/datagateway-dataview/src/views/card/dls/dlsVisitsCardView.component.tsx
  packages/datagateway-dataview/src/views/card/isis/isisDatasetsCardView.component.test.tsx
  packages/datagateway-dataview/src/views/card/isis/isisDatasetsCardView.component.tsx
  packages/datagateway-dataview/src/views/table/datasetTable.component.test.tsx
  packages/datagateway-dataview/src/views/table/datasetTable.component.tsx
  packages/datagateway-dataview/src/views/table/dls/dlsDatasetsTable.component.test.tsx
  packages/datagateway-dataview/src/views/table/dls/dlsDatasetsTable.component.tsx
  packages/datagateway-dataview/src/views/table/isis/isisDatasetsTable.component.test.tsx
  packages/datagateway-dataview/src/views/table/isis/isisDatasetsTable.component.tsx
Labels: MVP

#919 #914 - use selectAllSetting to stop sending allID requests
  packages/datagateway-common/src/api/index.test.tsx
  packages/datagateway-common/src/api/index.tsx
  packages/datagateway-common/src/api/investigations.test.tsx
  packages/datagateway-common/src/api/investigations.tsx
  packages/datagateway-common/src/views/addToCartButton.component.test.tsx
  packages/datagateway-common/src/views/addToCartButton.component.tsx
  packages/datagateway-dataview/src/views/table/__snapshots__/datafileTable.component.test.tsx.snap
  packages/datagateway-dataview/src/views/table/__snapshots__/datasetTable.component.test.tsx.snap
  packages/datagateway-dataview/src/views/table/__snapshots__/investigationTable.component.test.tsx.snap
  packages/datagateway-dataview/src/views/table/datafileTable.component.test.tsx
  packages/datagateway-dataview/src/views/table/datafileTable.component.tsx
  packages/datagateway-dataview/src/views/table/datasetTable.component.test.tsx
  packages/datagateway-dataview/src/views/table/datasetTable.component.tsx
  packages/datagateway-dataview/src/views/table/dls/dlsDatafilesTable.component.test.tsx
  packages/datagateway-dataview/src/views/table/dls/dlsDatafilesTable.component.tsx
  packages/datagateway-dataview/src/views/table/dls/dlsDatasetsTable.component.test.tsx
  packages/datagateway-dataview/src/views/table/dls/dlsDatasetsTable.component.tsx
  packages/datagateway-dataview/src/views/table/investigationTable.component.test.tsx
  packages/datagateway-dataview/src/views/table/investigationTable.component.tsx
  packages/datagateway-dataview/src/views/table/isis/__snapshots__/isisInvestigationsTable.component.test.tsx.snap
  packages/datagateway-dataview/src/views/table/isis/__snapshots__/isisMyDataTable.component.test.tsx.snap
  packages/datagateway-dataview/src/views/table/isis/isisDatafilesTable.component.test.tsx
  packages/datagateway-dataview/src/views/table/isis/isisDatafilesTable.component.tsx
  packages/datagateway-dataview/src/views/table/isis/isisDatasetsTable.component.test.tsx
  packages/datagateway-dataview/src/views/table/isis/isisDatasetsTable.component.tsx
  packages/datagateway-dataview/src/views/table/isis/isisInvestigationsTable.component.test.tsx
  packages/datagateway-dataview/src/views/table/isis/isisInvestigationsTable.component.tsx
  packages/datagateway-dataview/src/views/table/isis/isisMyDataTable.component.test.tsx
  packages/datagateway-dataview/src/views/table/isis/isisMyDataTable.component.tsx
  packages/datagateway-search/public/datagateway-search-settings.example.json
  packages/datagateway-search/src/__snapshots__/searchPageTable.test.tsx.snap
  packages/datagateway-search/src/card/datasetSearchCardView.component.test.tsx
  packages/datagateway-search/src/card/datasetSearchCardView.component.tsx
  packages/datagateway-search/src/card/investigationSearchCardView.component.test.tsx
  packages/datagateway-search/src/card/investigationSearchCardView.component.tsx
  packages/datagateway-search/src/state/actions/actions.test.tsx
  packages/datagateway-search/src/state/actions/actions.types.tsx
  packages/datagateway-search/src/state/actions/index.tsx
  packages/datagateway-search/src/state/app.types.tsx
  packages/datagateway-search/src/state/reducers/dgsearch.reducer.test.tsx
  packages/datagateway-search/src/state/reducers/dgsearch.reducer.tsx
  packages/datagateway-search/src/table/__snapshots__/datafileSearchTable.component.test.tsx.snap
  packages/datagateway-search/src/table/__snapshots__/datasetSearchTable.component.test.tsx.snap
  packages/datagateway-search/src/table/__snapshots__/investigationSearchTable.component.test.tsx.snap
  packages/datagateway-search/src/table/datafileSearchTable.component.test.tsx
  packages/datagateway-search/src/table/datafileSearchTable.component.tsx
  packages/datagateway-search/src/table/datasetSearchTable.component.test.tsx
  packages/datagateway-search/src/table/datasetSearchTable.component.tsx
  packages/datagateway-search/src/table/investigationSearchTable.component.test.tsx
  packages/datagateway-search/src/table/investigationSearchTable.component.tsx
Labels: MVP

#909 render study pid as link #857
  packages/datagateway-common/src/table/cellRenderers/cellContentRenderers.tsx
  packages/datagateway-dataview/cypress/integration/card/investigations.spec.ts
  packages/datagateway-dataview/cypress/integration/card/isis/investigations.spec.ts
  packages/datagateway-dataview/cypress/integration/card/isis/studies.spec.ts
  packages/datagateway-dataview/cypress/integration/landing/isis/investigation.spec.ts
  packages/datagateway-dataview/cypress/integration/landing/isis/study.spec.ts
  packages/datagateway-dataview/cypress/integration/table/investigations.spec.ts
  packages/datagateway-dataview/cypress/integration/table/isis/investigations.spec.ts
  packages/datagateway-dataview/cypress/integration/table/isis/myData.spec.ts
  packages/datagateway-dataview/cypress/integration/table/isis/studies.spec.ts
  packages/datagateway-dataview/src/views/card/isis/__snapshots__/isisStudiesCardView.component.test.tsx.snap
  packages/datagateway-dataview/src/views/card/isis/isisStudiesCardView.component.test.tsx
  packages/datagateway-dataview/src/views/card/isis/isisStudiesCardView.component.tsx
  packages/datagateway-dataview/src/views/detailsPanels/isis/investigationDetailsPanel.component.tsx
  packages/datagateway-dataview/src/views/landing/isis/isisInvestigationLanding.component.test.tsx
  packages/datagateway-dataview/src/views/landing/isis/isisInvestigationLanding.component.tsx
  packages/datagateway-dataview/src/views/landing/isis/isisStudyLanding.component.test.tsx
  packages/datagateway-dataview/src/views/landing/isis/isisStudyLanding.component.tsx
  packages/datagateway-dataview/src/views/table/investigationTable.component.test.tsx
  packages/datagateway-dataview/src/views/table/investigationTable.component.tsx
  packages/datagateway-dataview/src/views/table/isis/__snapshots__/isisInvestigationsTable.component.test.tsx.snap
  packages/datagateway-dataview/src/views/table/isis/__snapshots__/isisMyDataTable.component.test.tsx.snap
  packages/datagateway-dataview/src/views/table/isis/__snapshots__/isisStudiesTable.component.test.tsx.snap
  packages/datagateway-dataview/src/views/table/isis/isisInvestigationsTable.component.test.tsx
  packages/datagateway-dataview/src/views/table/isis/isisInvestigationsTable.component.tsx
  packages/datagateway-dataview/src/views/table/isis/isisMyDataTable.component.test.tsx
  packages/datagateway-dataview/src/views/table/isis/isisMyDataTable.component.tsx
  packages/datagateway-dataview/src/views/table/isis/isisStudiesTable.component.test.tsx
  packages/datagateway-dataview/src/views/table/isis/isisStudiesTable.component.tsx
  packages/datagateway-search/cypress/integration/searchPageContainer.spec.ts
  packages/datagateway-search/src/table/__snapshots__/investigationSearchTable.component.test.tsx.snap
  packages/datagateway-search/src/table/investigationSearchTable.component.test.tsx
  packages/datagateway-search/src/table/investigationSearchTable.component.tsx
Labels: datagateway-dataview

#926 Improve theme customisation #925
  packages/datagateway-common/src/homePage/homePage.component.tsx
  packages/datagateway-common/src/index.tsx
  packages/datagateway-common/src/table/columnFilters/dateColumnFilter.component.tsx
  packages/datagateway-common/src/views/selectionAlert.component.tsx
  packages/datagateway-dataview/src/page/pageContainer.component.tsx
  packages/datagateway-dataview/src/views/landing/isis/isisBranding.component.tsx
  packages/datagateway-search/src/search/datePicker.component.tsx
  packages/datagateway-search/src/searchPageCardView.tsx
  packages/datagateway-search/src/searchPageContainer.component.tsx
  packages/datagateway-search/src/searchPageTable.tsx
Labels: enhancement, accessibility

#942 Add message to search explaining only top 300 results are displayed (#937)
  packages/datagateway-search/public/res/default.json
  packages/datagateway-search/src/__snapshots__/searchBoxContainer.component.test.tsx.snap
  packages/datagateway-search/src/searchBoxContainer.component.tsx
Labels: enhancement, user feedback

#934 Replace resizable icons with lines between columns in tables (#929)
  packages/datagateway-common/src/table/cellRenderers/__snapshots__/dataCell.component.test.tsx.snap
  packages/datagateway-common/src/table/cellRenderers/dataCell.component.tsx
  packages/datagateway-common/src/table/headerRenderers/__snapshots__/dataHeader.component.test.tsx.snap
  packages/datagateway-common/src/table/headerRenderers/dataHeader.component.tsx
  packages/datagateway-common/src/table/table.component.tsx
Labels: enhancement, user feedback

#944 Add links on homepage #943
  packages/datagateway-common/src/api/index.tsx
  packages/datagateway-common/src/homePage/__snapshots__/homePage.component.test.tsx.snap
  packages/datagateway-common/src/homePage/homePage.component.test.tsx
  packages/datagateway-common/src/homePage/homePage.component.tsx
  packages/datagateway-dataview/cypress/integration/homePage.spec.ts
  packages/datagateway-dataview/public/res/default.json
  packages/datagateway-dataview/src/page/__snapshots__/translatedHomePage.component.test.tsx.snap
  packages/datagateway-dataview/src/page/translatedHomePage.component.tsx
  packages/datagateway-search/src/searchPageContainer.component.test.tsx
  packages/datagateway-search/src/searchPageContainer.component.tsx
Labels: enhancement, MVP, user feedback

#955 Fix styling on advanced filters in search card view and make date filter errors more specific #951 #952
  packages/datagateway-common/src/table/columnFilters/__snapshots__/dateColumnFilter.component.test.tsx.snap
  packages/datagateway-common/src/table/columnFilters/dateColumnFilter.component.test.tsx
  packages/datagateway-common/src/table/columnFilters/dateColumnFilter.component.tsx
  packages/datagateway-search/cypress/integration/searchBoxContainer.spec.ts
  packages/datagateway-search/public/res/default.json
  packages/datagateway-search/src/search/datePicker.component.test.tsx
  packages/datagateway-search/src/search/datePicker.component.tsx
  packages/datagateway-search/src/searchPageContainer.component.tsx
Labels: bug, datagateway-search, datagateway-common, accessibility
